#!/usr/bin/env python3
"""
Sex scene generator v2 - generates images per persona/story/scene.
Structure: sex_pics/{persona}_sex/story_{N}/schene_{N}/

Usage:
  python generate_sex_scenes.py <persona> <story> <scene> [num_images]
  python generate_sex_scenes.py <persona> <story> all [num_images]
  python generate_sex_scenes.py <persona> all all [num_images]

Examples:
  python generate_sex_scenes.py sasha 1 1 20     # Sasha, story 1, scene 1, 20 images
  python generate_sex_scenes.py sasha 1 all 15    # Sasha, story 1, all scenes, 15 each
  python generate_sex_scenes.py sasha all all 15   # Sasha, all stories, all scenes, 15 each
"""

import json
import os
import sys
import time
import random
import urllib.request
import urllib.error

COMFYUI_URL = "http://195.209.210.175:8188"
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FLOW_DIR = os.path.join(BASE_DIR, "sex_flow_api")
PICS_DIR = os.path.join(BASE_DIR, "sex_pics")

# ── Default pose prompts (no story context — generic bedroom) ────────────────
DEFAULT_POSE_PROMPTS = {
    1: "wide angle overhead view of intimate scene on bed, woman lying on her back in missionary position with man on top between her legs, camera positioned above and slightly to the side capturing full view of her body and face, woman lying flat on her back with legs spread wide apart and knees bent upward, her thighs open and feet resting on mattress, arms wrapped around his back or gripping sheets beside her, head resting on pillow looking up at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing deep arousal, long hair spread across white pillow beneath her head, her breasts and torso clearly visible beneath him, man positioned between her legs with his torso partially covering her body and face out of frame, active penetration clearly visible from above angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, woman's vulva and inner thighs in clear focus along with her face, both sets of genitalia fully visible and anatomically correct, white rumpled bedding beneath them, modern bedroom interior with soft afternoon light, warm diffused natural lighting from large window creating gentle highlights on her skin and body, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, detailed facial features with natural skin texture showing visible pores, arousal flush on face chest and thighs, realistic genitalia with natural coloration and moisture, erotic intimate adult scene showing full penetration, professional boudoir photography style, balanced depth of field keeping both face and genitalia in sharp focus, 8k ultra high quality, cinematic warm color grading with golden tones, passionate intimate atmosphere, natural body positioning with proper anatomy",
    2: "rear three-quarter view on bed, woman on all fours doggy style with man kneeling behind her, back arched naturally with hips raised, head turned looking back at camera with pleasure expression and parted lips, hair over one shoulder, breasts visible from side, man gripping her hips with face out of frame, penetration visible from rear angle with anatomically correct genitalia, white bedding modern bedroom soft afternoon light, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
    3: "frontal view on bed, woman sitting on top of man in cowgirl position facing camera, man lying on his back beneath her with face out of frame, woman upright straddling his hips with knees on mattress, back slightly arched chest forward, hands resting on his chest for support, looking directly at camera with pleasure expression and parted lips, hair falling around shoulders, breasts fully visible, penetration visible from front with anatomically correct genitalia, white bedding modern bedroom soft afternoon light, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
    4: "wide angle frontal view of intimate scene on bed, woman in reverse cowgirl position straddling man who lies beneath her, camera positioned low at foot of bed capturing full frontal view, woman sitting upright facing camera with back arched and chest pushed forward, her legs spread wide on either side straddling his hips with knees bent and feet planted on bed, hands resting on his thighs behind her for support, head tilted slightly back looking directly at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing arousal, long hair cascading down her back and shoulders, her breasts and torso clearly visible in frame, man's body beneath her with only his torso and hips visible with face out of frame, active penetration clearly visible from front angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, woman's vulva and inner thighs in clear focus along with her face, both sets of genitalia fully visible and anatomically correct, white rumpled bedding beneath them, modern bedroom interior with soft afternoon light, warm diffused natural lighting from large window creating gentle highlights on her skin and body, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, detailed facial features with natural skin texture showing visible pores, arousal flush on face chest and thighs, realistic genitalia with natural coloration and moisture, erotic intimate adult scene showing full penetration, professional boudoir photography style, balanced depth of field keeping both face and genitalia in sharp focus, 8k ultra high quality, cinematic warm color grading with golden tones, passionate intimate atmosphere, natural body positioning with proper anatomy",
    5: "side angle view in bedroom, man and woman standing having sex from behind, woman facing away from him leaning slightly forward with hands braced against wall, back arched naturally pushing hips back, head turned to side with pleasure expression and parted lips, breasts visible from side, man standing close behind her gripping her hip with face out of frame, penetration visible from side angle with anatomically correct genitalia, modern bedroom soft afternoon light, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
    6: "POV male perspective looking down, woman lying flat on her stomach on bed, her back and buttocks visible from above, head turned to side on pillow with pleasure expression and parted lips, hair spread on pillow, his hands gripping her hips, penetration visible from above POV angle his erect penis entering her vulva from behind, her buttocks and lower back in foreground, white rumpled bedding, modern bedroom soft afternoon light, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
    7: "POV male perspective looking down from above at woman pressed against wall, woman facing the wall with her back to camera, her back and buttocks visible from above, head turned to side looking back over shoulder with pleasure expression and parted lips, hair falling to one side, his hand on her hip, penetration visible from behind POV angle his erect penis entering her vulva, her buttocks in foreground, modern bedroom wall soft afternoon light, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
    8: "POV male perspective looking down from above, woman lying on her back on bed with legs pulled up to her chest, her face visible looking up at camera with pleasure expression and parted lips, hair spread on pillow, breasts visible between her raised thighs, his hands gripping her thighs holding them up, penetration visible from above POV angle his erect penis entering her vulva, her vulva and face both in frame, white rumpled bedding, modern bedroom soft afternoon light, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
    9: "POV male perspective looking down from above, woman on all fours on bed with deep arch in her lower back, her back curved downward and buttocks raised high toward camera, head down between her arms with hair falling forward, his hands on her lower back gripping her waist from both sides, penetration visible from above POV angle his erect penis entering her vulva from behind, her arched back and buttocks in foreground, white rumpled bedding, modern bedroom soft afternoon light, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
    10: "POV male perspective lying on back looking up, woman sitting on top straddling hips leaning back with arms behind her resting on his legs for support, her body arched backward with chest and breasts pushed upward, head tilted back with pleasure expression and parted lips, hair falling behind her, her torso and breasts visible from below, penetration visible from below POV angle his erect penis entering her vulva, her body silhouetted against ceiling light, white rumpled bedding, modern bedroom soft afternoon light, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
}

# ── Story-specific prompts per persona ───────────────────────────────────────
# Format: STORY_PROMPTS[persona][story_num][scene_num] = "prompt"
# If a persona/story/scene combo is not here, falls back to DEFAULT_POSE_PROMPTS
STORY_PROMPTS = {
    "sasha": {
        1: {  # Auction — luxury VIP room, red silk, glamorous lighting
            1: "wide angle overhead view of intimate scene, woman lying on her back in missionary position with man on top between her legs, camera positioned above and slightly to the side capturing full view of her body and face, woman lying flat on her back with legs spread wide apart and knees bent upward, her thighs open, arms wrapped around his back or gripping red silk sheets beside her, head resting on pillow looking up at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing deep arousal, long hair spread across pillow beneath her head, her breasts and torso clearly visible beneath him, man positioned between her legs with his torso partially covering her body and face out of frame, active penetration clearly visible from above angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, woman's vulva and inner thighs in clear focus along with her face, both sets of genitalia fully visible and anatomically correct, red silk draped luxury VIP room, opulent glamorous setting, gold accents, warm glamorous party lighting with amber glow, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, arousal flush on face chest and thighs, 8k ultra high quality, cinematic warm color grading with golden tones",
            2: "rear three-quarter view, woman on all fours doggy style with man kneeling behind her, back arched naturally with hips raised, head turned looking back at camera with pleasure expression and parted lips, hair over one shoulder, breasts visible from side, man gripping her hips with face out of frame, penetration visible from rear angle with anatomically correct genitalia, red silk draped luxury VIP room, opulent glamorous setting, gold accents, warm glamorous party lighting with amber glow, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            3: "frontal view, woman sitting on top of man in cowgirl position facing camera, man lying on his back beneath her with face out of frame, woman upright straddling his hips with knees on surface, back slightly arched chest forward, hands resting on his chest for support, looking directly at camera with pleasure expression and parted lips, hair falling around shoulders, breasts fully visible, penetration visible from front with anatomically correct genitalia, red silk draped luxury VIP room, opulent glamorous setting, gold accents, warm glamorous party lighting with amber glow, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            4: "wide angle frontal view of intimate scene, woman in reverse cowgirl position straddling man who lies beneath her, camera positioned low capturing full frontal view, woman sitting upright facing camera with back arched and chest pushed forward, her legs spread wide on either side straddling his hips with knees bent, hands resting on his thighs behind her for support, head tilted slightly back looking directly at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing arousal, long hair cascading down her back and shoulders, her breasts and torso clearly visible in frame, man's body beneath her with only his torso and hips visible with face out of frame, active penetration clearly visible from front angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, both sets of genitalia fully visible and anatomically correct, red silk draped luxury VIP room, opulent glamorous setting, gold accents, warm glamorous party lighting with amber glow, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, arousal flush on face chest and thighs, 8k ultra high quality, cinematic warm color grading with golden tones",
            5: "side angle view, man and woman standing having sex from behind, woman facing away from him leaning slightly forward with hands braced against wall, back arched naturally pushing hips back, head turned to side with pleasure expression and parted lips, breasts visible from side, man standing close behind her gripping her hip with face out of frame, penetration visible from side angle with anatomically correct genitalia, red silk draped luxury VIP room, opulent glamorous setting, gold accents, warm glamorous party lighting with amber glow, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            6: "POV male perspective looking down, woman lying flat on her stomach, her back and buttocks visible from above, head turned to side with pleasure expression and parted lips, hair spread to side, his hands gripping her hips, penetration visible from above POV angle his erect penis entering her vulva from behind, her buttocks and lower back in foreground, red silk sheets beneath her, luxury VIP room, opulent glamorous setting, gold accents, warm glamorous lighting with amber glow, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            7: "POV male perspective looking down from above at woman pressed against wall, woman facing the wall with her back to camera, her back and buttocks visible from above, head turned to side looking back over shoulder with pleasure expression and parted lips, hair falling to one side, his hand on her hip, penetration visible from behind POV angle his erect penis entering her vulva, her buttocks in foreground, luxury VIP room wall with red silk drapes, opulent glamorous setting, gold accents, warm glamorous lighting with amber glow, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            8: "POV male perspective looking down from above, woman lying on her back with legs pulled up to her chest, her face visible looking up at camera with pleasure expression and parted lips, hair spread on pillow, breasts visible between her raised thighs, his hands gripping her thighs holding them up, penetration visible from above POV angle his erect penis entering her vulva, her vulva and face both in frame, red silk sheets beneath her, luxury VIP room, opulent glamorous setting, gold accents, warm glamorous lighting with amber glow, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            9: "POV male perspective looking down from above, woman on all fours with deep arch in her lower back, her back curved downward and buttocks raised high toward camera, head down between her arms with hair falling forward, his hands on her lower back gripping her waist from both sides, penetration visible from above POV angle his erect penis entering her vulva from behind, her arched back and buttocks in foreground, red silk sheets beneath her, luxury VIP room, opulent glamorous setting, gold accents, warm glamorous lighting with amber glow, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            10: "POV male perspective lying on back looking up, woman sitting on top straddling hips leaning back with arms behind her resting on his legs for support, her body arched backward with chest and breasts pushed upward, head tilted back with pleasure expression and parted lips, hair falling behind her, her torso and breasts visible from below, penetration visible from below POV angle his erect penis entering her vulva, her body silhouetted against ceiling light, red silk draped luxury VIP room, opulent glamorous setting, warm glamorous lighting with amber glow from above, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
        },
        2: {  # Plane — first class cabin, leather seats, soft cabin lighting
            1: "wide angle overhead view of intimate scene, woman lying on her back in missionary position with man on top between her legs, camera positioned above and slightly to the side capturing full view of her body and face, woman lying flat on her back with legs spread wide apart and knees bent upward, her thighs open, arms wrapped around his back or gripping leather seat, head resting looking up at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing deep arousal, long hair spread beneath her head, her breasts and torso clearly visible beneath him, man positioned between her legs with his torso partially covering her body and face out of frame, active penetration clearly visible from above angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, woman's vulva and inner thighs in clear focus along with her face, both sets of genitalia fully visible and anatomically correct, first class airplane cabin interior, luxurious leather seats reclined flat, soft cabin lighting, window with clouds visible, enclosed intimate space, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, arousal flush on face chest and thighs, 8k ultra high quality, cinematic warm color grading with golden tones",
            2: "rear three-quarter view, woman on all fours doggy style with man kneeling behind her, back arched naturally with hips raised, head turned looking back at camera with pleasure expression and parted lips, hair over one shoulder, breasts visible from side, man gripping her hips with face out of frame, penetration visible from rear angle with anatomically correct genitalia, first class airplane cabin interior, luxurious leather seats, soft cabin lighting, window with clouds visible, enclosed intimate space, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            3: "frontal view, woman sitting on top of man in cowgirl position facing camera, man lying on his back beneath her with face out of frame, woman upright straddling his hips with knees on reclined leather seat, back slightly arched chest forward, hands resting on his chest for support, looking directly at camera with pleasure expression and parted lips, hair falling around shoulders, breasts fully visible, penetration visible from front with anatomically correct genitalia, first class airplane cabin interior, luxurious leather seats reclined flat, soft cabin lighting, window with clouds visible, enclosed intimate space, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            4: "wide angle frontal view of intimate scene, woman in reverse cowgirl position straddling man who lies beneath her, camera positioned low capturing full frontal view, woman sitting upright facing camera with back arched and chest pushed forward, her legs spread wide on either side straddling his hips with knees bent, hands resting on his thighs behind her for support, head tilted slightly back looking directly at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing arousal, long hair cascading down her back and shoulders, her breasts and torso clearly visible in frame, man's body beneath her with only his torso and hips visible with face out of frame, active penetration clearly visible from front angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, both sets of genitalia fully visible and anatomically correct, first class airplane cabin interior, luxurious leather seats reclined flat, soft cabin lighting, window with clouds visible, enclosed intimate space, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, arousal flush on face chest and thighs, 8k ultra high quality, cinematic warm color grading with golden tones",
            5: "side angle view, man and woman standing having sex from behind, woman facing away from him leaning slightly forward with hands braced against cabin wall, back arched naturally pushing hips back, head turned to side with pleasure expression and parted lips, breasts visible from side, man standing close behind her gripping her hip with face out of frame, penetration visible from side angle with anatomically correct genitalia, first class airplane cabin interior, luxurious cabin wall, soft cabin lighting, window with clouds visible, enclosed intimate space, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            6: "POV male perspective looking down, woman lying flat on her stomach, her back and buttocks visible from above, head turned to side with pleasure expression and parted lips, hair spread to side, his hands gripping her hips, penetration visible from above POV angle his erect penis entering her vulva from behind, her buttocks and lower back in foreground, reclined first class airplane seat beneath her, luxurious leather surface, soft cabin lighting, window with clouds visible, enclosed intimate space, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            7: "POV male perspective looking down from above at woman pressed against cabin wall, woman facing the wall with her back to camera, her back and buttocks visible from above, head turned to side looking back over shoulder with pleasure expression and parted lips, hair falling to one side, his hand on her hip, penetration visible from behind POV angle his erect penis entering her vulva, her buttocks in foreground, first class airplane cabin wall, soft cabin lighting, window with clouds visible, enclosed intimate space, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            8: "POV male perspective looking down from above, woman lying on her back with legs pulled up to her chest, her face visible looking up at camera with pleasure expression and parted lips, hair spread beneath her, breasts visible between her raised thighs, his hands gripping her thighs holding them up, penetration visible from above POV angle his erect penis entering her vulva, her vulva and face both in frame, reclined first class airplane seat beneath her, luxurious leather surface, soft cabin lighting, window with clouds visible, enclosed intimate space, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            9: "POV male perspective looking down from above, woman on all fours with deep arch in her lower back, her back curved downward and buttocks raised high toward camera, head down between her arms with hair falling forward, his hands on her lower back gripping her waist from both sides, penetration visible from above POV angle his erect penis entering her vulva from behind, her arched back and buttocks in foreground, reclined first class airplane seat beneath her, luxurious leather surface, soft cabin lighting, window with clouds visible, enclosed intimate space, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            10: "POV male perspective lying on back looking up, woman sitting on top straddling hips leaning back with arms behind her resting on his legs for support, her body arched backward with chest and breasts pushed upward, head tilted back with pleasure expression and parted lips, hair falling behind her, her torso and breasts visible from below, penetration visible from below POV angle his erect penis entering her vulva, her body silhouetted against overhead cabin light, first class airplane cabin ceiling, soft cabin lighting from above, enclosed intimate space, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
        },
        3: {  # Party — VIP room, purple neon, leather sofa, moody
            1: "wide angle overhead view of intimate scene, woman lying on her back in missionary position with man on top between her legs, camera positioned above and slightly to the side capturing full view of her body and face, woman lying flat on her back with legs spread wide apart and knees bent upward, her thighs open, arms wrapped around his back or gripping leather sofa, head resting on cushion looking up at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing deep arousal, long hair spread beneath her head, her breasts and torso clearly visible beneath him, man positioned between her legs with his torso partially covering her body and face out of frame, active penetration clearly visible from above angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, woman's vulva and inner thighs in clear focus along with her face, both sets of genitalia fully visible and anatomically correct, VIP room at exclusive party, leather sofa, dim purple neon lights, moody party lighting, dark atmospheric setting, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, arousal flush on face chest and thighs, 8k ultra high quality, cinematic moody color grading with purple tones",
            2: "rear three-quarter view, woman on all fours doggy style with man kneeling behind her, back arched naturally with hips raised, head turned looking back at camera with pleasure expression and parted lips, hair over one shoulder, breasts visible from side, man gripping her hips with face out of frame, penetration visible from rear angle with anatomically correct genitalia, VIP room at exclusive party, leather sofa, dim purple neon lights, moody party lighting, dark atmospheric setting, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with purple tones, professional boudoir photography",
            3: "frontal view, woman sitting on top of man in cowgirl position facing camera, man lying on his back beneath her with face out of frame, woman upright straddling his hips with knees on leather sofa, back slightly arched chest forward, hands resting on his chest for support, looking directly at camera with pleasure expression and parted lips, hair falling around shoulders, breasts fully visible, penetration visible from front with anatomically correct genitalia, VIP room at exclusive party, leather sofa, dim purple neon lights, moody party lighting, dark atmospheric setting, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with purple tones, professional boudoir photography",
            4: "wide angle frontal view of intimate scene, woman in reverse cowgirl position straddling man who lies beneath her, camera positioned low capturing full frontal view, woman sitting upright facing camera with back arched and chest pushed forward, her legs spread wide on either side straddling his hips with knees bent, hands resting on his thighs behind her for support, head tilted slightly back looking directly at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing arousal, long hair cascading down her back and shoulders, her breasts and torso clearly visible in frame, man's body beneath her with only his torso and hips visible with face out of frame, active penetration clearly visible from front angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, both sets of genitalia fully visible and anatomically correct, VIP room at exclusive party, leather sofa, dim purple neon lights, moody party lighting, dark atmospheric setting, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, arousal flush on face chest and thighs, 8k ultra high quality, cinematic moody color grading with purple tones",
            5: "side angle view, man and woman standing having sex from behind, woman facing away from him leaning slightly forward with hands braced against wall, back arched naturally pushing hips back, head turned to side with pleasure expression and parted lips, breasts visible from side, man standing close behind her gripping her hip with face out of frame, penetration visible from side angle with anatomically correct genitalia, VIP room at exclusive party, dark wall, dim purple neon lights, moody party lighting, dark atmospheric setting, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with purple tones, professional boudoir photography",
            6: "POV male perspective looking down, woman lying flat on her stomach, her back and buttocks visible from above, head turned to side with pleasure expression and parted lips, hair spread to side, his hands gripping her hips, penetration visible from above POV angle his erect penis entering her vulva from behind, her buttocks and lower back in foreground, leather sofa beneath her, VIP room at exclusive party, dim purple neon lights, moody party lighting, dark atmospheric setting, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with purple tones, professional boudoir photography",
            7: "POV male perspective looking down from above at woman pressed against wall, woman facing the wall with her back to camera, her back and buttocks visible from above, head turned to side looking back over shoulder with pleasure expression and parted lips, hair falling to one side, his hand on her hip, penetration visible from behind POV angle his erect penis entering her vulva, her buttocks in foreground, VIP room dark wall at exclusive party, dim purple neon lights, moody party lighting, dark atmospheric setting, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with purple tones, professional boudoir photography",
            8: "POV male perspective looking down from above, woman lying on her back with legs pulled up to her chest, her face visible looking up at camera with pleasure expression and parted lips, hair spread on cushion, breasts visible between her raised thighs, his hands gripping her thighs holding them up, penetration visible from above POV angle his erect penis entering her vulva, her vulva and face both in frame, leather sofa beneath her, VIP room at exclusive party, dim purple neon lights, moody party lighting, dark atmospheric setting, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with purple tones, professional boudoir photography",
            9: "POV male perspective looking down from above, woman on all fours with deep arch in her lower back, her back curved downward and buttocks raised high toward camera, head down between her arms with hair falling forward, his hands on her lower back gripping her waist from both sides, penetration visible from above POV angle his erect penis entering her vulva from behind, her arched back and buttocks in foreground, leather sofa beneath her, VIP room at exclusive party, dim purple neon lights, moody party lighting, dark atmospheric setting, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with purple tones, professional boudoir photography",
            10: "POV male perspective lying on back looking up, woman sitting on top straddling hips leaning back with arms behind her resting on his legs for support, her body arched backward with chest and breasts pushed upward, head tilted back with pleasure expression and parted lips, hair falling behind her, her torso and breasts visible from below, penetration visible from below POV angle his erect penis entering her vulva, her body silhouetted against dim ceiling, VIP room at exclusive party, dim purple neon lights from above, moody party lighting, dark atmospheric setting, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with purple tones, professional boudoir photography",
        },
    },
    "lina": {
        1: {  # Sauna — wooden benches, steam, warm golden amber lighting
            1: "wide angle overhead view of intimate scene, woman lying on her back in missionary position with man on top between her legs, camera positioned above and slightly to the side capturing full view of her body and face, woman lying flat on her back with legs spread wide apart and knees bent upward, her thighs open, arms wrapped around his back or gripping wooden bench beneath her, head resting looking up at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing deep arousal, long hair spread beneath her head, her breasts and torso clearly visible beneath him, man positioned between her legs with his torso partially covering her body and face out of frame, active penetration clearly visible from above angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, woman's vulva and inner thighs in clear focus along with her face, both sets of genitalia fully visible and anatomically correct, wooden sauna interior, wooden benches, steam atmosphere, warm golden amber lighting, dewy glistening skin with moisture, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, arousal flush on face chest and thighs, 8k ultra high quality, cinematic warm color grading with golden tones",
            2: "rear three-quarter view, woman on all fours doggy style with man kneeling behind her, back arched naturally with hips raised, head turned looking back at camera with pleasure expression and parted lips, hair over one shoulder, breasts visible from side, man gripping her hips with face out of frame, penetration visible from rear angle with anatomically correct genitalia, wooden sauna interior, wooden benches, steam atmosphere, warm golden amber lighting, dewy glistening skin with moisture, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            3: "frontal view, woman sitting on top of man in cowgirl position facing camera, man lying on his back beneath her with face out of frame, woman upright straddling his hips with knees on wooden bench, back slightly arched chest forward, hands resting on his chest for support, looking directly at camera with pleasure expression and parted lips, hair falling around shoulders, breasts fully visible, penetration visible from front with anatomically correct genitalia, wooden sauna interior, wooden benches, steam atmosphere, warm golden amber lighting, dewy glistening skin with moisture, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            4: "wide angle frontal view of intimate scene, woman in reverse cowgirl position straddling man who lies beneath her, camera positioned low capturing full frontal view, woman sitting upright facing camera with back arched and chest pushed forward, her legs spread wide on either side straddling his hips with knees bent, hands resting on his thighs behind her for support, head tilted slightly back looking directly at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing arousal, long hair cascading down her back and shoulders, her breasts and torso clearly visible in frame, man's body beneath her with only his torso and hips visible with face out of frame, active penetration clearly visible from front angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, both sets of genitalia fully visible and anatomically correct, wooden sauna interior, wooden benches, steam atmosphere, warm golden amber lighting, dewy glistening skin with moisture, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, arousal flush on face chest and thighs, 8k ultra high quality, cinematic warm color grading with golden tones",
            5: "side angle view, man and woman standing having sex from behind, woman facing away from him leaning slightly forward with hands braced against wooden sauna wall, back arched naturally pushing hips back, head turned to side with pleasure expression and parted lips, breasts visible from side, man standing close behind her gripping her hip with face out of frame, penetration visible from side angle with anatomically correct genitalia, wooden sauna interior, wooden wall and benches, steam atmosphere, warm golden amber lighting, dewy glistening skin with moisture, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            6: "POV male perspective looking down, woman lying flat on her stomach, her back and buttocks visible from above, head turned to side with pleasure expression and parted lips, hair spread to side, his hands gripping her hips, penetration visible from above POV angle his erect penis entering her vulva from behind, her buttocks and lower back in foreground, wooden sauna bench beneath her, wooden sauna interior, steam atmosphere, warm golden amber lighting, dewy glistening skin with moisture, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            7: "POV male perspective looking down from above at woman pressed against wall, woman facing the wooden wall with her back to camera, her back and buttocks visible from above, head turned to side looking back over shoulder with pleasure expression and parted lips, hair falling to one side, his hand on her hip, penetration visible from behind POV angle his erect penis entering her vulva, her buttocks in foreground, wooden sauna wall, steam atmosphere, warm golden amber lighting, dewy glistening skin with moisture, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            8: "POV male perspective looking down from above, woman lying on her back with legs pulled up to her chest, her face visible looking up at camera with pleasure expression and parted lips, hair spread beneath her, breasts visible between her raised thighs, his hands gripping her thighs holding them up, penetration visible from above POV angle his erect penis entering her vulva, her vulva and face both in frame, wooden sauna bench beneath her, wooden sauna interior, steam atmosphere, warm golden amber lighting, dewy glistening skin with moisture, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            9: "POV male perspective looking down from above, woman on all fours with deep arch in her lower back, her back curved downward and buttocks raised high toward camera, head down between her arms with hair falling forward, his hands on her lower back gripping her waist from both sides, penetration visible from above POV angle his erect penis entering her vulva from behind, her arched back and buttocks in foreground, wooden sauna bench beneath her, wooden sauna interior, steam atmosphere, warm golden amber lighting, dewy glistening skin with moisture, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            10: "POV male perspective lying on back looking up, woman sitting on top straddling hips leaning back with arms behind her resting on his legs for support, her body arched backward with chest and breasts pushed upward, head tilted back with pleasure expression and parted lips, hair falling behind her, her torso and breasts visible from below, penetration visible from below POV angle his erect penis entering her vulva, her body silhouetted against wooden sauna ceiling, wooden sauna interior, steam atmosphere, warm golden amber lighting from above, dewy glistening skin with moisture, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
        },
        2: {  # Shower — bathroom, tile walls, glass door, wet skin, steam
            1: "wide angle overhead view of intimate scene, woman lying on her back in missionary position with man on top between her legs, camera positioned above and slightly to the side capturing full view of her body and face, woman lying flat on her back with legs spread wide apart and knees bent upward, her thighs open, arms wrapped around his back, head resting looking up at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing deep arousal, wet hair clinging to skin, her breasts and torso clearly visible beneath him, man positioned between her legs with his torso partially covering her body and face out of frame, active penetration clearly visible from above angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, woman's vulva and inner thighs in clear focus along with her face, both sets of genitalia fully visible and anatomically correct, bathroom shower setting, white tile walls, glass shower door, water droplets on skin, wet glistening bodies, steam and humidity, soft warm bathroom lighting, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, arousal flush on face chest and thighs, 8k ultra high quality, cinematic warm color grading with golden tones",
            2: "rear three-quarter view, woman on all fours doggy style with man kneeling behind her, back arched naturally with hips raised, head turned looking back at camera with pleasure expression and parted lips, wet hair over one shoulder, breasts visible from side, man gripping her hips with face out of frame, penetration visible from rear angle with anatomically correct genitalia, bathroom shower setting, white tile walls, glass shower door, water droplets on skin, wet glistening bodies, steam and humidity, soft warm bathroom lighting, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            3: "frontal view, woman sitting on top of man in cowgirl position facing camera, man lying on his back beneath her with face out of frame, woman upright straddling his hips, back slightly arched chest forward, hands resting on his chest for support, looking directly at camera with pleasure expression and parted lips, wet hair falling around shoulders, breasts fully visible, penetration visible from front with anatomically correct genitalia, bathroom shower setting, white tile walls, glass shower door, water droplets on skin, wet glistening bodies, steam and humidity, soft warm bathroom lighting, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            4: "wide angle frontal view of intimate scene, woman in reverse cowgirl position straddling man who lies beneath her, camera positioned low capturing full frontal view, woman sitting upright facing camera with back arched and chest pushed forward, her legs spread wide on either side straddling his hips with knees bent, hands resting on his thighs behind her for support, head tilted slightly back looking directly at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing arousal, wet hair cascading down her back and shoulders, her breasts and torso clearly visible in frame, man's body beneath her with only his torso and hips visible with face out of frame, active penetration clearly visible from front angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, both sets of genitalia fully visible and anatomically correct, bathroom shower setting, white tile walls, glass shower door, water droplets on skin, wet glistening bodies, steam and humidity, soft warm bathroom lighting, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, arousal flush on face chest and thighs, 8k ultra high quality, cinematic warm color grading with golden tones",
            5: "side angle view, man and woman standing having sex from behind, woman facing away from him leaning slightly forward with hands braced against wet tile wall, back arched naturally pushing hips back, head turned to side with pleasure expression and parted lips, breasts visible from side, man standing close behind her gripping her hip with face out of frame, penetration visible from side angle with anatomically correct genitalia, bathroom shower setting, white tile walls, glass shower door, water droplets on skin, wet glistening bodies, steam and humidity, soft warm bathroom lighting, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            6: "POV male perspective looking down, woman lying flat on her stomach, her back and buttocks visible from above, head turned to side with pleasure expression and parted lips, wet hair spread to side, his hands gripping her hips, penetration visible from above POV angle his erect penis entering her vulva from behind, her buttocks and lower back in foreground, wet tile floor beneath her, bathroom shower setting, water droplets on skin, wet glistening bodies, steam and humidity, soft warm bathroom lighting, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            7: "POV male perspective looking down from above at woman pressed against wall, woman facing the wet tile wall with her back to camera, her back and buttocks visible from above, head turned to side looking back over shoulder with pleasure expression and parted lips, wet hair falling to one side, his hand on her hip, penetration visible from behind POV angle his erect penis entering her vulva, her buttocks in foreground, bathroom tile wall, water droplets on skin, wet glistening bodies, steam and humidity, soft warm bathroom lighting, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            8: "POV male perspective looking down from above, woman lying on her back with legs pulled up to her chest, her face visible looking up at camera with pleasure expression and parted lips, wet hair spread beneath her, breasts visible between her raised thighs, his hands gripping her thighs holding them up, penetration visible from above POV angle his erect penis entering her vulva, her vulva and face both in frame, wet tile floor beneath her, bathroom shower setting, water droplets on skin, wet glistening bodies, steam and humidity, soft warm bathroom lighting, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            9: "POV male perspective looking down from above, woman on all fours with deep arch in her lower back, her back curved downward and buttocks raised high toward camera, head down between her arms with wet hair falling forward, his hands on her lower back gripping her waist from both sides, penetration visible from above POV angle his erect penis entering her vulva from behind, her arched back and buttocks in foreground, wet tile floor beneath her, bathroom shower setting, water droplets on skin, wet glistening bodies, steam and humidity, soft warm bathroom lighting, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
            10: "POV male perspective lying on back looking up, woman sitting on top straddling hips leaning back with arms behind her resting on his legs for support, her body arched backward with chest and breasts pushed upward, head tilted back with pleasure expression and parted lips, wet hair falling behind her, her torso and breasts visible from below, penetration visible from below POV angle his erect penis entering her vulva, her body silhouetted against bathroom ceiling light, shower setting, water droplets on skin, wet glistening bodies, steam and humidity, soft warm bathroom lighting from above, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic warm golden tones, professional boudoir photography",
        },
        3: {  # Gym — dark empty gym at night, dim lighting, equipment
            1: "wide angle overhead view of intimate scene, woman lying on her back in missionary position with man on top between her legs, camera positioned above and slightly to the side capturing full view of her body and face, woman lying flat on her back with legs spread wide apart and knees bent upward, her thighs open, arms wrapped around his back or gripping exercise mat beneath her, head resting looking up at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing deep arousal, long hair spread beneath her head, her breasts and torso clearly visible beneath him, man positioned between her legs with his torso partially covering her body and face out of frame, active penetration clearly visible from above angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, woman's vulva and inner thighs in clear focus along with her face, both sets of genitalia fully visible and anatomically correct, dark empty gym interior at night, fitness equipment in background, dim low key lighting, deep shadows, moody dark atmosphere, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, arousal flush on face chest and thighs, 8k ultra high quality, cinematic moody color grading with dark warm tones",
            2: "rear three-quarter view, woman on all fours doggy style with man kneeling behind her, back arched naturally with hips raised, head turned looking back at camera with pleasure expression and parted lips, hair over one shoulder, breasts visible from side, man gripping her hips with face out of frame, penetration visible from rear angle with anatomically correct genitalia, dark empty gym interior at night, fitness equipment in background, dim low key lighting, deep shadows, moody dark atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with dark warm tones, professional boudoir photography",
            3: "frontal view, woman sitting on top of man in cowgirl position facing camera, man lying on his back beneath her with face out of frame, woman upright straddling his hips with knees on exercise mat, back slightly arched chest forward, hands resting on his chest for support, looking directly at camera with pleasure expression and parted lips, hair falling around shoulders, breasts fully visible, penetration visible from front with anatomically correct genitalia, dark empty gym interior at night, fitness equipment in background, dim low key lighting, deep shadows, moody dark atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with dark warm tones, professional boudoir photography",
            4: "wide angle frontal view of intimate scene, woman in reverse cowgirl position straddling man who lies beneath her, camera positioned low capturing full frontal view, woman sitting upright facing camera with back arched and chest pushed forward, her legs spread wide on either side straddling his hips with knees bent, hands resting on his thighs behind her for support, head tilted slightly back looking directly at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing arousal, long hair cascading down her back and shoulders, her breasts and torso clearly visible in frame, man's body beneath her with only his torso and hips visible with face out of frame, active penetration clearly visible from front angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, both sets of genitalia fully visible and anatomically correct, dark empty gym interior at night, fitness equipment in background, dim low key lighting, deep shadows, moody dark atmosphere, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, arousal flush on face chest and thighs, 8k ultra high quality, cinematic moody color grading with dark warm tones",
            5: "side angle view, man and woman standing having sex from behind, woman facing away from him leaning slightly forward with hands braced against gym wall, back arched naturally pushing hips back, head turned to side with pleasure expression and parted lips, breasts visible from side, man standing close behind her gripping her hip with face out of frame, penetration visible from side angle with anatomically correct genitalia, dark empty gym interior at night, fitness equipment in background, dim low key lighting, deep shadows, moody dark atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with dark warm tones, professional boudoir photography",
            6: "POV male perspective looking down, woman lying flat on her stomach, her back and buttocks visible from above, head turned to side with pleasure expression and parted lips, hair spread to side, his hands gripping her hips, penetration visible from above POV angle his erect penis entering her vulva from behind, her buttocks and lower back in foreground, exercise mat beneath her, dark empty gym interior at night, dim low key lighting, deep shadows, moody dark atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with dark warm tones, professional boudoir photography",
            7: "POV male perspective looking down from above at woman pressed against wall, woman facing the gym wall with her back to camera, her back and buttocks visible from above, head turned to side looking back over shoulder with pleasure expression and parted lips, hair falling to one side, his hand on her hip, penetration visible from behind POV angle his erect penis entering her vulva, her buttocks in foreground, dark empty gym wall at night, dim low key lighting, deep shadows, moody dark atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with dark warm tones, professional boudoir photography",
            8: "POV male perspective looking down from above, woman lying on her back with legs pulled up to her chest, her face visible looking up at camera with pleasure expression and parted lips, hair spread beneath her, breasts visible between her raised thighs, his hands gripping her thighs holding them up, penetration visible from above POV angle his erect penis entering her vulva, her vulva and face both in frame, exercise mat beneath her, dark empty gym interior at night, dim low key lighting, deep shadows, moody dark atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with dark warm tones, professional boudoir photography",
            9: "POV male perspective looking down from above, woman on all fours with deep arch in her lower back, her back curved downward and buttocks raised high toward camera, head down between her arms with hair falling forward, his hands on her lower back gripping her waist from both sides, penetration visible from above POV angle his erect penis entering her vulva from behind, her arched back and buttocks in foreground, exercise mat beneath her, dark empty gym interior at night, dim low key lighting, deep shadows, moody dark atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with dark warm tones, professional boudoir photography",
            10: "POV male perspective lying on back looking up, woman sitting on top straddling hips leaning back with arms behind her resting on his legs for support, her body arched backward with chest and breasts pushed upward, head tilted back with pleasure expression and parted lips, hair falling behind her, her torso and breasts visible from below, penetration visible from below POV angle his erect penis entering her vulva, her body silhouetted against dark gym ceiling, dark empty gym interior at night, dim low key lighting from above, deep shadows, moody dark atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic moody color grading with dark warm tones, professional boudoir photography",
        },
        4: {  # Trainer — gym interior, weight bench, dramatic spotlight
            1: "wide angle overhead view of intimate scene, woman lying on her back in missionary position with man on top between her legs, camera positioned above and slightly to the side capturing full view of her body and face, woman lying flat on her back with legs spread wide apart and knees bent upward, her thighs open, arms wrapped around his back or gripping exercise bench beneath her, head resting looking up at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing deep arousal, long hair spread beneath her head, her breasts and torso clearly visible beneath him, man positioned between her legs with his torso partially covering her body and face out of frame, active penetration clearly visible from above angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, woman's vulva and inner thighs in clear focus along with her face, both sets of genitalia fully visible and anatomically correct, gym interior, weight bench, exercise equipment visible, dramatic spotlight lighting, athletic atmosphere, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, arousal flush on face chest and thighs, 8k ultra high quality, cinematic dramatic color grading with warm contrast tones",
            2: "rear three-quarter view, woman on all fours doggy style with man kneeling behind her, back arched naturally with hips raised, head turned looking back at camera with pleasure expression and parted lips, hair over one shoulder, breasts visible from side, man gripping her hips with face out of frame, penetration visible from rear angle with anatomically correct genitalia, gym interior, weight bench nearby, exercise equipment visible, dramatic spotlight lighting, athletic atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic dramatic color grading with warm contrast tones, professional boudoir photography",
            3: "frontal view, woman sitting on top of man in cowgirl position facing camera, man lying on his back beneath her with face out of frame, woman upright straddling his hips with knees on weight bench, back slightly arched chest forward, hands resting on his chest for support, looking directly at camera with pleasure expression and parted lips, hair falling around shoulders, breasts fully visible, penetration visible from front with anatomically correct genitalia, gym interior, weight bench, exercise equipment visible, dramatic spotlight lighting, athletic atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic dramatic color grading with warm contrast tones, professional boudoir photography",
            4: "wide angle frontal view of intimate scene, woman in reverse cowgirl position straddling man who lies beneath her, camera positioned low capturing full frontal view, woman sitting upright facing camera with back arched and chest pushed forward, her legs spread wide on either side straddling his hips with knees bent, hands resting on his thighs behind her for support, head tilted slightly back looking directly at camera with intense pleasure expression and mouth open, passionate eye contact with viewer showing arousal, long hair cascading down her back and shoulders, her breasts and torso clearly visible in frame, man's body beneath her with only his torso and hips visible with face out of frame, active penetration clearly visible from front angle showing his erect penis entering her vulva, labia spread naturally around shaft during penetration, both sets of genitalia fully visible and anatomically correct, gym interior, weight bench, exercise equipment visible, dramatic spotlight lighting, athletic atmosphere, photorealistic rendering with subtle film grain texture, anatomically correct bodies with realistic proportions, arousal flush on face chest and thighs, 8k ultra high quality, cinematic dramatic color grading with warm contrast tones",
            5: "side angle view, man and woman standing having sex from behind, woman facing away from him leaning slightly forward with hands braced against gym mirror wall, back arched naturally pushing hips back, head turned to side with pleasure expression and parted lips, breasts visible from side, man standing close behind her gripping her hip with face out of frame, penetration visible from side angle with anatomically correct genitalia, gym interior, mirrors on wall, exercise equipment visible, dramatic spotlight lighting, athletic atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic dramatic color grading with warm contrast tones, professional boudoir photography",
            6: "POV male perspective looking down, woman lying flat on her stomach, her back and buttocks visible from above, head turned to side with pleasure expression and parted lips, hair spread to side, his hands gripping her hips, penetration visible from above POV angle his erect penis entering her vulva from behind, her buttocks and lower back in foreground, exercise bench beneath her, gym interior, exercise equipment visible, dramatic spotlight lighting, athletic atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic dramatic color grading with warm contrast tones, professional boudoir photography",
            7: "POV male perspective looking down from above at woman pressed against wall, woman facing the gym mirror wall with her back to camera, her back and buttocks visible from above, head turned to side looking back over shoulder with pleasure expression and parted lips, hair falling to one side, his hand on her hip, penetration visible from behind POV angle his erect penis entering her vulva, her buttocks in foreground, gym mirror wall, exercise equipment visible, dramatic spotlight lighting, athletic atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic dramatic color grading with warm contrast tones, professional boudoir photography",
            8: "POV male perspective looking down from above, woman lying on her back with legs pulled up to her chest, her face visible looking up at camera with pleasure expression and parted lips, hair spread beneath her, breasts visible between her raised thighs, his hands gripping her thighs holding them up, penetration visible from above POV angle his erect penis entering her vulva, her vulva and face both in frame, exercise bench beneath her, gym interior, exercise equipment visible, dramatic spotlight lighting, athletic atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic dramatic color grading with warm contrast tones, professional boudoir photography",
            9: "POV male perspective looking down from above, woman on all fours with deep arch in her lower back, her back curved downward and buttocks raised high toward camera, head down between her arms with hair falling forward, his hands on her lower back gripping her waist from both sides, penetration visible from above POV angle his erect penis entering her vulva from behind, her arched back and buttocks in foreground, exercise bench beneath her, gym interior, exercise equipment visible, dramatic spotlight lighting, athletic atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic dramatic color grading with warm contrast tones, professional boudoir photography",
            10: "POV male perspective lying on back looking up, woman sitting on top straddling hips leaning back with arms behind her resting on his legs for support, her body arched backward with chest and breasts pushed upward, head tilted back with pleasure expression and parted lips, hair falling behind her, her torso and breasts visible from below, penetration visible from below POV angle his erect penis entering her vulva, her body silhouetted against gym ceiling spotlight, gym interior, exercise equipment visible, dramatic spotlight lighting from above, athletic atmosphere, photorealistic subtle film grain, natural skin texture with arousal flush, 8k ultra high quality, cinematic dramatic color grading with warm contrast tones, professional boudoir photography",
        },
    },
    # Add more personas here as prompts are created...
}

# ── Lora triggers per persona ────────────────────────────────────────────────
PERSONA_TRIGGERS = {
    "anastasia": "",
    "ash": "brit-woman, ",
    "honney": "l34n0r, chubby woman, ",
    "julie": "elvaross, ",
    "lina": "ameg2, ",
    "marianna": "Amanda_Z, a beautiful woman with ginger hair, braided hair, green eyes and full lips, ",
    "mei": "asig2, ",
    "pai": "ameg2, ",
    "roxy": "Chase Infinity, African American, young woman, slicked back braided cornrows hairstyle, ",
    "sasha": "eurameg1, ",
    "stacy": "woman037, ",
    "taya": "Elise_XWMB, she has blonde hair, ",
    "una": "ee1st_asn, a beautiful woman with ginger hair, braided hair, green eyes and full lips, ",
}

# ── Persona config: flow file, pics folder, number of stories ────────────────
PERSONA_MAP = {
    "anastasia": {"flow": "ANASTASIA_SEX_FLOW.json", "pics": "anastasia_sex", "stories": 2},
    "ash":       {"flow": "ASH_SEX_FLOW.json",       "pics": "ash_sex",       "stories": 2},
    "honney":    {"flow": "HONNEY_SEX_FLOW.json",     "pics": "honney_sex",    "stories": 3},
    "julie":     {"flow": "JULIE_SEX_FLOW.json",      "pics": "julie_sex",     "stories": 3},
    "lina":      {"flow": "LINA_SEX_FLOW.json",       "pics": "lina_sex",      "stories": 4},
    "marianna":  {"flow": "MARIANNA_SEX_FLOW.json",   "pics": "marriana_sex",  "stories": 4},
    "mei":       {"flow": "MEI_SEX_FLOW.json",        "pics": "mei_sex",       "stories": 4},
    "pai":       {"flow": "PAI_SEX_FLOW.json",        "pics": "pai_sex",       "stories": 3},
    "roxy":      {"flow": "ROXY_SEX_FLOW.json",       "pics": "roxy_sex",      "stories": 3},
    "sasha":     {"flow": "SASHA_SEX_FLOW.json",      "pics": "sasha_sex",     "stories": 3},
    "stacy":     {"flow": "STACY_SEX_FLOW.json",      "pics": "stacy_sex",     "stories": 4},
    "taya":      {"flow": "TAYA_SEX_FLOW.json",       "pics": "taya_sex",      "stories": 4},
    "una":       {"flow": "UNA_SEX_FLOW.json",        "pics": "una_sex",       "stories": 3},
}


def get_prompt(persona: str, story_num: int, scene_num: int) -> str:
    """Get the prompt for a specific persona/story/scene combo.
    Falls back to default pose prompt if no story-specific prompt exists."""
    if persona in STORY_PROMPTS:
        if story_num in STORY_PROMPTS[persona]:
            if scene_num in STORY_PROMPTS[persona][story_num]:
                return STORY_PROMPTS[persona][story_num][scene_num]
    return DEFAULT_POSE_PROMPTS[scene_num]


def queue_prompt(workflow: dict) -> str:
    """Send prompt to ComfyUI and return prompt_id."""
    payload = json.dumps({"prompt": workflow}).encode("utf-8")
    req = urllib.request.Request(
        f"{COMFYUI_URL}/prompt",
        data=payload,
        headers={"Content-Type": "application/json"},
    )
    resp = urllib.request.urlopen(req)
    result = json.loads(resp.read())
    return result["prompt_id"]


def wait_for_completion(prompt_id: str, timeout: int = 120) -> dict:
    """Poll ComfyUI history until prompt completes."""
    start = time.time()
    while time.time() - start < timeout:
        try:
            resp = urllib.request.urlopen(f"{COMFYUI_URL}/history/{prompt_id}")
            history = json.loads(resp.read())
            if prompt_id in history:
                return history[prompt_id]
        except Exception:
            pass
        time.sleep(2)
    raise TimeoutError(f"Prompt {prompt_id} didn't complete in {timeout}s")


def download_image(filename: str, subfolder: str, save_path: str):
    """Download generated image from ComfyUI."""
    url = f"{COMFYUI_URL}/view?filename={filename}&subfolder={subfolder}&type=output"
    urllib.request.urlretrieve(url, save_path)


def generate_scene(persona: str, story_num: int, scene_num: int, num_images: int = 20):
    """Generate images for one persona + one story + one scene."""
    info = PERSONA_MAP[persona]
    flow_path = os.path.join(FLOW_DIR, info["flow"])
    save_dir = os.path.join(PICS_DIR, info["pics"], f"story_{story_num}", f"schene_{scene_num}")
    os.makedirs(save_dir, exist_ok=True)

    # Check how many already exist
    existing = len([f for f in os.listdir(save_dir) if f.endswith(".png")])
    if existing >= num_images:
        print(f"  [SKIP] {persona} story {story_num} scene {scene_num}: already has {existing} images")
        return

    with open(flow_path) as f:
        workflow = json.load(f)

    # Build prompt: lora trigger + story-specific pose prompt
    trigger = PERSONA_TRIGGERS[persona]
    pose_prompt = get_prompt(persona, story_num, scene_num)
    full_prompt = trigger + pose_prompt

    # Check if using story-specific or default prompt
    has_story_prompt = (persona in STORY_PROMPTS
                        and story_num in STORY_PROMPTS.get(persona, {})
                        and scene_num in STORY_PROMPTS.get(persona, {}).get(story_num, {}))
    prompt_type = "STORY" if has_story_prompt else "DEFAULT"

    # Set prompt in node 4
    workflow["4"]["inputs"]["text"] = full_prompt

    print(f"\n{'='*80}")
    print(f"  {persona.upper()} — Story {story_num} — Scene {scene_num} [{prompt_type}]")
    print(f"  Prompt: {full_prompt[:100]}...")
    print(f"  Saving to: {save_dir}")
    print(f"  Generating {num_images - existing} images (already have {existing})")
    print(f"{'='*60}")

    for i in range(existing + 1, num_images + 1):
        # Randomize seed for each image
        workflow["7"]["inputs"]["seed"] = random.randint(1, 2**53)
        if "11" in workflow:
            workflow["11"]["inputs"]["seed"] = random.randint(1, 2**53)
        if "14" in workflow:
            workflow["14"]["inputs"]["seed"] = random.randint(1, 2**53)
        if "15" in workflow:
            workflow["15"]["inputs"]["seed"] = random.randint(1, 2**53)

        try:
            prompt_id = queue_prompt(workflow)
            print(f"  [{i}/{num_images}] Queued: {prompt_id[:8]}...", end=" ", flush=True)

            result = wait_for_completion(prompt_id, timeout=120)

            outputs = result.get("outputs", {})
            saved = False
            for node_id, node_output in outputs.items():
                if "images" in node_output:
                    for img in node_output["images"]:
                        filename = img["filename"]
                        subfolder = img.get("subfolder", "")
                        save_path = os.path.join(save_dir, f"{i:03d}.png")
                        download_image(filename, subfolder, save_path)
                        size_mb = os.path.getsize(save_path) / 1024 / 1024
                        print(f"OK ({size_mb:.1f}MB)")
                        saved = True
                        break
                if saved:
                    break

            if not saved:
                print("WARN: no output image found")

        except Exception as e:
            print(f"ERROR: {e}")
            time.sleep(5)


def main():
    if len(sys.argv) < 2:
        print("Usage:")
        print("  python generate_sex_scenes.py <persona> <story> <scene> [num_images]")
        print("  python generate_sex_scenes.py <persona> <story> all [num_images]")
        print("  python generate_sex_scenes.py <persona> all all [num_images]")
        print()
        print("Examples:")
        print("  python generate_sex_scenes.py sasha 1 1 20       # Sasha story 1, scene 1, 20 imgs")
        print("  python generate_sex_scenes.py sasha 1 all 15      # Sasha story 1, all 10 scenes")
        print("  python generate_sex_scenes.py sasha all all 15     # Sasha all stories, all scenes")
        print()
        print(f"Personas: {', '.join(sorted(PERSONA_MAP.keys()))}")
        print()
        print("Stories per persona:")
        for p in sorted(PERSONA_MAP.keys()):
            n = PERSONA_MAP[p]["stories"]
            has_prompts = "✅ story prompts" if p in STORY_PROMPTS else "⚠️  default prompts"
            print(f"  {p}: {n} stories — {has_prompts}")
        sys.exit(1)

    persona = sys.argv[1].lower()

    if persona not in PERSONA_MAP:
        print(f"Unknown persona: {persona}")
        print(f"Available: {', '.join(sorted(PERSONA_MAP.keys()))}")
        sys.exit(1)

    info = PERSONA_MAP[persona]
    num_stories = info["stories"]

    if len(sys.argv) < 3:
        print("Error: specify story number or 'all'")
        sys.exit(1)

    story_arg = sys.argv[2].lower()
    scene_arg = sys.argv[3].lower() if len(sys.argv) > 3 else "all"
    num_images = int(sys.argv[4]) if len(sys.argv) > 4 else 20

    # If scene_arg is a number and num_images not explicitly set, check if it's num_images
    if scene_arg != "all":
        try:
            scene_val = int(scene_arg)
            if len(sys.argv) > 4:
                num_images = int(sys.argv[4])
        except ValueError:
            pass

    # Determine story range
    if story_arg == "all":
        stories = range(1, num_stories + 1)
    else:
        stories = [int(story_arg)]

    # Determine scene range
    if scene_arg == "all":
        scenes = range(1, 11)
    else:
        scenes = [int(scene_arg)]

    # Validate
    for s in stories:
        if s < 1 or s > num_stories:
            print(f"Error: {persona} has {num_stories} stories, got story {s}")
            sys.exit(1)
    for sc in scenes:
        if sc < 1 or sc > 10:
            print(f"Error: scene must be 1-10, got {sc}")
            sys.exit(1)

    # Generate
    total = len(list(stories)) * len(list(scenes))
    print(f"\n🎬 {persona.upper()}: {len(list(stories))} stories × {len(list(scenes))} scenes = {total} combos, {num_images} images each")

    for story in stories:
        for scene in scenes:
            generate_scene(persona, story, scene, num_images)

    print("\n✅ Done!")


if __name__ == "__main__":
    main()
